app/routes/orders.py
from flask import Blueprint, abort, flash, redirect, render_template, url_for

from app.forms.forms import AddItemsForm, NewOrderForm

from ..models import Employee, MenuItem, Order, OrderDetail, Table, db

bp = Blueprint("orders", __name__, url_prefix="")

@bp.route('/new_order', methods=['GET', 'POST'])
def new_order():
    form = NewOrderForm()

    # only employees and open tables
    form.employee_id.choices = [(employee.id, employee.name) for employee in Employee.query.all()]

    # find tables that are available / unoccupied
    open_table_ids = [order.table_id for order in Order.query.filter_by(finished=False).all()]
    available_tables = Table.query.filter(~Table.id.in_(open_table_ids)).all()

    # only populate form's dropdown with available tables
    form.table_id.choices = [(table.id, f"Table {table.number} (Seats {table.capacity})") for table in available_tables]

    # submit form
    if form.validate_on_submit():
        order = Order(
            employee_id = form.employee_id.data,
            table_id = form.table_id.data,
            finished = False
        )

        db.session.add(order)
        db.session.commit()
        return redirect(url_for("orders.view_order", order_id=order.id))

    return render_template("orders/new_order.html", form=form)

@bp.route("/<int:order_id>")
def view_order(order_id):
    order =Order.query.get(order_id)
    if not order:
        abort(404)

    return render_template("orders/order_view.html", order=order)

@bp.route("/<int:order_id>/add_items", methods=['GET', 'POST'])
def add_items(order_id):
    order = Order.query.get_or_404(order_id)
    form = AddItemsForm()

    # populate dropdown with all menu items
    form.menu_items.choices = [(item.id, f"{item.name} (${item.price:.2f})") for item in MenuItem.query.all()]

    if form.validate_on_submit():
        print("form validated on submit")
        for menu_item_id in form.menu_items.data:
            item = OrderDetail(menu_item_id=menu_item_id, order=order)
            db.session.add(item)

        db.session.commit()
        flash("Items successfully added to order!", "success")
        return redirect(url_for("orders.view_order", order_id=order.id))

    return render_template("orders/add_items.html", order=order, form=form)


@bp.route("/<int:order_id>/close", methods=['POST'])
def close_order(order_id):
    order = Order.query.get_or_404(order_id)

    if order.finished:
        flash('Order is already closed. ', "info")
    else:
        order.finished = True
        db.session.commit()
        flash("Order has been closed.", "success")

    return redirect(url_for("orders.view_order", order_id=order.id))

app/templates/orders/add_items.html
{% extends "base.html" %}
{% block content %}
    <h1>Add Items to Order #{{ order.id }}</h1>
    <form method="post">
        {{ form.hidden_tag() }}
        <div>
            {{ form.menu_items.label }} <br>
            {% for subfield in form.menu_items %}
                <label>{{ subfield() }} {{ subfield.label.text }}</label>
            {% endfor %}
        </div>
        <div>{{ form.submit() }}</div>
    </form>
    <br>
    <a href="{{ url_for('orders.view_order', order_id=order.id) }}">Back to Order</a>

{% endblock %}

app/templates/orders/new_order.html
{% extends "base.html" %}
{% block content %}
<h1>Assign Employee to Table</h1>
<form action="" method="post">
    {{ form.csrf_token() }}

    <div>
        {{ form.employee_id.label }} {{ form.employee_id() }}
    </div>
    <div>
        {{ form.table_id.label }} {{ form.table_id() }}
    </div>

    <div>{{ form.submit() }}</div>

</form>
{% endblock %}

app/templates/orders/order_view.html
{% extends "base.html" %}

{% block content %}
<h1>Order #{{ order.id }}</h1>
<p><strong>Table:</strong> {{ order.table.number }}</p>
<p><strong>Server:</strong> {{ order.employee.name }}</p>
<p><strong>Status:</strong>{{ "Closed" if order.finished else "Open" }}</p>

<h2>Items</h2>
{% if order.details %}
<ul>
    {% for detail in order.details %}
    <li>{{ detail.menu_item.name }} - ${{ "%.2f"|format(detail.menu_item.price) }}</li>
    {% endfor %}
</ul>
{% else %}
<p>No items yet.</p>
{% endif %}

{% if not order.finished %}
<a href="{{ url_for('orders.add_items', order_id=order.id) }}">Add Food Item</a> <br>
<form method="post" action="{{ url_for('orders.close_order', order_id=order.id)}}">
    <button type="submit">Close Order</button>
</form>
{% endif %}

{% endblock %}